[package]
name = "scope-backend-discord"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atomic_refcell = "0.1"
catty = "0.1"
chrono.workspace = true
dashmap = "6"
gpui.workspace = true
log.workspace = true
querystring = "1.1"
rand.workspace = true
scope-backend-cache = { path = "../cache" }
scope-chat.workspace = true
scope-rich.workspace = true
serenity = { git = "https://github.com/scopeclient/serenity", version = "0.12" }
tokio.workspace = true
url = "2"

[dev-dependencies]
serde_json = "1"
